---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
library(ggplot2)
library(readxl)
```

 

```{r}
write_csv(roman_empire,"re_data/roman_empire.csv")



roman_empire <- read_csv("re_data/roman_empire.csv")

roman_empire
```

  NUMBER CITIES BY IMPERIAL PROVINCE


```{r}
count_cities <- roman_empire %>% 
  group_by(province) %>% 
  summarise(counts = n())


count_cities
``` 
  
```{r}
 ggplot(count_cities)+
    geom_bar(aes(x = province, y = counts ), stat = 'identity')+
    ylab("Number of cities") +
      xlab("Province") +
      labs(title  = "Number odf cities by Imperial Province") +
      theme(axis.text.x = element_text(angle=45, hjust=1))
  
```

NUMBER CITIES BY MODERN COUNTRIES


```{r}
count_cities_by_country <- roman_empire %>% 
  group_by(country) %>% 
  summarise(counts = n())

count_cities_by_country
```
  
```{r}
ggplot(count_cities_by_country)+
    geom_bar(aes(x = country, y = counts ), stat = 'identity')+
    ylab("Number of cities") +
      xlab("country") +
      labs(title  = "Number odf cities by nowadays countries") +
      theme(axis.text.x = element_text(angle=45, hjust=1))
```
  
  
  
  how many cities have this status?
  
  
```{r}

roman_empire %>%
      filter(province ) %>% #== input$imperial_province2) %>%
      filter(civic_status) %>% # == input$status) %>%
      filter (country) %>%  #== input$country2) %>% 
      ggplot(aes(x = modern_toponym , y = province , fill = civic_status))+
      geom_col()+
      theme(axis.text.x = element_text(angle = 45, hjust = 1, face = 'italic'))+
      labs(x = "Actual Name",
           y = "Roman Province")

```

```{r}
roman_empire <- roman_empire %>% 
  mutate(continent = country) %>% 
  mutate(continent=recode(continent,"Greece" = "Europe", 
                          "Albania" = "Europe","Egypt" = "Africa","Tunisia" ="Africa","Libya" = "Africa","Italy" = "Europe","France" = "Europe","Jordan" = "Asia", "Syria" = "Asia","Turkey" = "Asia","Israel" = "Asia","Spain" = "Europe","Bulgaria" = "Europe","Croatia"= "Europe", "Bosnia and Herzegovina" ="Europe","Cyprus" ="Europe", "Germany"= "Europe", "Austria" = "Europe","Hungary"="Europe","Lebanon" = "Asia","Macedonia" ="Europe","Malta"="Europe","Montenegro"="Europe","Morocco"="Africa","Netherlands"= "Europe","Northern Cyprus" = "Europe", "Portugal" ="Europe","Romania"= "Europe","Serbia"= "Europe", "Slovenia"= "Europe", "Spain"= "Europe","Switzerland"="Europe","Tunisia"= "Africa","United Kingdom" = "Europe"))
  

view(roman_empire)
```

  
  
  
  
 
  


